version: '3.9'

services:
  db:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5430:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
            mkdir -p /usr/local/etc/redis &&
            echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
            echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
            echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
            echo "user default off" > /usr/local/etc/redis/users.acl &&
            echo "user $REDIS_USER on >$REDIS_PASS ~* +@all" >> /usr/local/etc/redis/users.acl &&
            redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
          '
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "$REDIS_USER", "--pass", "$REDIS_PASS", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true