"""alter column user_id in tables

Revision ID: 67b0f3c1d5fb
Revises: d7e8d3e33e18
Create Date: 2025-12-22 00:30:40.078350

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b0f3c1d5fb'
down_revision: Union[str, None] = 'd7e8d3e33e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'])
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'user_id')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###