"""delete column user_id from answers

Revision ID: d7e8d3e33e18
Revises: ff6a64d9f3d1
Create Date: 2025-12-22 00:30:02.279199

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8d3e33e18'
down_revision: Union[str, None] = 'ff6a64d9f3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###