"""delete column user_id in users

Revision ID: ff6a64d9f3d1
Revises: 73365d1b8a9c
Create Date: 2025-12-20 19:17:55.988525

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6a64d9f3d1'
down_revision: Union[str, None] = '73365d1b8a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###